FROM centos:7
MAINTAINER manuel.peuster@uni-paderborn.de

RUN yum-config-manager --add-repo https://vault.centos.org/centos/7.9.2009/os/x86_64/
RUN yum update -y
RUN yum install -y \
    net-tools \
    iproute \
    iputils-ping

CMD /bin/bash
